### ISSUE TITLE
meteor-client bundle fails

### ISSUE THREAD

**Issue by terrytompkins** [Urigo/React-Meteor-Todo-app#3]
I've tried several versions of node/npm in conjunction with meteor 1.5.  The results are the same as shown below using node 7.10.0:
C02PH2QEFVH8:React-Meteor-Todo-app ttompkins$ npm install
npm WARN sass-loader@6.0.6 requires a peer of webpack@^2.0.0 || >= 3.0.0-rc.0 || ^3.0.0 but none was installed.
C02PH2QEFVH8:React-Meteor-Todo-app ttompkins$ npm run bundle-meteor-client

> react-meteor-todo-app@ bundle-meteor-client /Users/ttompkins/src/Meteor/test/MeteorClientBundlerTest/React-Meteor-Todo-app
> meteor-client bundle -s api --url=localhost:8000

Created a new Meteor app in '/var/folders/cc/br3q390s28q1rwx6vlth5g6c0000gn/T/tmp-50198ZNhaZ0Up8FaI'.

To run your new app:                          
  cd /var/folders/cc/br3q390s28q1rwx6vlth5g6c0000gn/T/tmp-50198ZNhaZ0Up8FaI
  meteor                                      
                                              
If you are new to Meteor, try some of the learning resources here:
  https://www.meteor.com/learn                
                                              
meteor create --bare to create an empty app.  
meteor create --full to create a scaffolded app.
                                              
=> Errors while initializing project:         
                                              
While selecting package versions:
error: No version of standard-minifier-js satisfies all constraints: @1.2.2, @2.1.0
Constraints on package "standard-minifier-js":
* standard-minifier-js@1.2.2 <- top level
* standard-minifier-js@2.1.0 <- top level

/Users/ttompkins/src/Meteor/test/MeteorClientBundlerTest/React-Meteor-Todo-app/node_modules/execa/index.js:277
		throw (result.error || new Error(result.stderr === '' ? result.stdout : result.stderr));
		^

Error: null
    at Function.module.exports.sync (/Users/ttompkins/src/Meteor/test/MeteorClientBundlerTest/React-Meteor-Todo-app/node_modules/execa/index.js:277:26)
    at Object.bundle (/Users/ttompkins/src/Meteor/test/MeteorClientBundlerTest/React-Meteor-Todo-app/node_modules/meteor-client-bundler/lib/bundler.js:72:9)
    at Command.<anonymous> (/Users/ttompkins/src/Meteor/test/MeteorClientBundlerTest/React-Meteor-Todo-app/node_modules/meteor-client-bundler/cli:37:13)
    at Command.listener (/Users/ttompkins/src/Meteor/test/MeteorClientBundlerTest/React-Meteor-Todo-app/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:194:7)
    at Command.parseArgs (/Users/ttompkins/src/Meteor/test/MeteorClientBundlerTest/React-Meteor-Todo-app/node_modules/commander/index.js:615:12)
    at Command.parse (/Users/ttompkins/src/Meteor/test/MeteorClientBundlerTest/React-Meteor-Todo-app/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/Users/ttompkins/src/Meteor/test/MeteorClientBundlerTest/React-Meteor-Todo-app/node_modules/meteor-client-bundler/cli:45:9)
    at Module._compile (module.js:571:32)

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/ttompkins/.nvm/versions/node/v7.10.0/bin/node" "/Users/ttompkins/.nvm/versions/node/v7.10.0/bin/npm" "run" "bundle-meteor-client"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-meteor-todo-app@ bundle-meteor-client: `meteor-client bundle -s api --url=localhost:8000`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-meteor-todo-app@ bundle-meteor-client script 'meteor-client bundle -s api --url=localhost:8000'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-meteor-todo-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     meteor-client bundle -s api --url=localhost:8000
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-meteor-todo-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-meteor-todo-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ttompkins/.npm/_logs/2017-06-28T14_32_05_544Z-debug.log
C02PH2QEFVH8:React-Meteor-Todo-app ttompkins$ meteor --version
Meteor 1.5
C02PH2QEFVH8:React-Meteor-Todo-app ttompkins$ node --version
v7.10.0
C02PH2QEFVH8:React-Meteor-Todo-app ttompkins$ npm --version
4.2.0

-------------------------
The content of the referenced log file are as follows:

0 info it worked if it ends with ok
1 verbose cli [ '/Users/ttompkins/.nvm/versions/node/v7.10.0/bin/node',
1 verbose cli   '/Users/ttompkins/.nvm/versions/node/v7.10.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'bundle-meteor-client' ]
2 info using npm@4.2.0
3 info using node@v7.10.0
4 verbose run-script [ 'prebundle-meteor-client',
4 verbose run-script   'bundle-meteor-client',
4 verbose run-script   'postbundle-meteor-client' ]
5 info lifecycle react-meteor-todo-app@~prebundle-meteor-client: react-meteor-todo-app@
6 silly lifecycle react-meteor-todo-app@~prebundle-meteor-client: no script for prebundle-meteor-client, continuing
7 info lifecycle react-meteor-todo-app@~bundle-meteor-client: react-meteor-todo-app@
8 verbose lifecycle react-meteor-todo-app@~bundle-meteor-client: unsafe-perm in lifecycle true
9 verbose lifecycle react-meteor-todo-app@~bundle-meteor-client: PATH: /Users/ttompkins/.nvm/versions/node/v7.10.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/ttompkins/src/Meteor/test/MeteorClientBundlerTest/React-Meteor-Todo-app/node_modules/.bin:/Users/ttompkins/.nvm/versions/node/v7.10.0/bin:/Users/ttompkins/Downloads/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
10 verbose lifecycle react-meteor-todo-app@~bundle-meteor-client: CWD: /Users/ttompkins/src/Meteor/test/MeteorClientBundlerTest/React-Meteor-Todo-app
11 silly lifecycle react-meteor-todo-app@~bundle-meteor-client: Args: [ '-c', 'meteor-client bundle -s api --url=localhost:8000' ]
12 silly lifecycle react-meteor-todo-app@~bundle-meteor-client: Returned: code: 1  signal: null
13 info lifecycle react-meteor-todo-app@~bundle-meteor-client: Failed to exec bundle-meteor-client script
14 verbose stack Error: react-meteor-todo-app@ bundle-meteor-client: `meteor-client bundle -s api --url=localhost:8000`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/ttompkins/.nvm/versions/node/v7.10.0/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/ttompkins/.nvm/versions/node/v7.10.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid react-meteor-todo-app@
16 verbose cwd /Users/ttompkins/src/Meteor/test/MeteorClientBundlerTest/React-Meteor-Todo-app
17 error Darwin 15.6.0
18 error argv "/Users/ttompkins/.nvm/versions/node/v7.10.0/bin/node" "/Users/ttompkins/.nvm/versions/node/v7.10.0/bin/npm" "run" "bundle-meteor-client"
19 error node v7.10.0
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 1
23 error react-meteor-todo-app@ bundle-meteor-client: `meteor-client bundle -s api --url=localhost:8000`
23 error Exit status 1
24 error Failed at the react-meteor-todo-app@ bundle-meteor-client script 'meteor-client bundle -s api --url=localhost:8000'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the react-meteor-todo-app package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     meteor-client bundle -s api --url=localhost:8000
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs react-meteor-todo-app
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls react-meteor-todo-app
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by zetekla** [comment]
Same issue here:

`                                              
meteor create --bare to create an empty app.  
meteor create --full to create a scaffolded app.
                                              
up to date in 0.464s
=> Errors while initializing project:         
                                              
While selecting package versions:
error: No version of standard-minifier-js satisfies all constraints: @1.2.2, @~2.2.0
Constraints on package "standard-minifier-js":
* standard-minifier-js@1.2.2 <- top level
* standard-minifier-js@~2.2.0 <- top level

/Users/admin/Research/React-Meteor-Todo-app/node_modules/execa/index.js:277
                throw (result.error || new Error(result.stderr === '' ? result.stdout : result.stderr));
                ^

Error: null
    at Function.module.exports.sync (/Users/admin/Research/React-Meteor-Todo-app/node_modules/execa/index.js:277:26)
    at Object.bundle (/Users/admin/Research/React-Meteor-Todo-app/node_modules/meteor-client-bundler/lib/bundler.js:72:9)
    at Command.<anonymous> (/Users/admin/Research/React-Meteor-Todo-app/node_modules/meteor-client-bundler/cli:37:13)
    at Command.listener (/Users/admin/Research/React-Meteor-Todo-app/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:125:13)
    at Command.emit (events.js:213:7)
    at Command.parseArgs (/Users/admin/Research/React-Meteor-Todo-app/node_modules/commander/index.js:653:12)
    at Command.parse (/Users/admin/Research/React-Meteor-Todo-app/node_modules/commander/index.js:475:21)
    at Object.<anonymous> (/Users/admin/Research/React-Meteor-Todo-app/node_modules/meteor-client-bundler/cli:45:9)
    at Module._compile (module.js:624:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-meteor-todo-app@ bundle-meteor-client: `meteor-client bundle -s api --url=localhost:8000`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-meteor-todo-app@ bundle-meteor-client script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2017-12-29T19_20_53_725Z-debug.log
`

**Comment by miguelalarcos** [comment]
Same issue here
