### ISSUE TITLE
Errors while initializing project ( package versions standard-minifier-js )

### ISSUE THREAD

**Issue by gustawdaniel** [Urigo/React-Meteor-Todo-app#68]
Failing on step

    npm run bundle-meteor-client

With logs:

```
> react-meteor-todo-app@ bundle-meteor-client /home/daniel/exp/MCB/React-Meteor-Todo-app
> meteor-client bundle -s api --url=localhost:8000

Created a new Meteor app in '/tmp/tmp-16553kbXSSGyXp8s0'.

To run your new app:                          
  cd /tmp/tmp-16553kbXSSGyXp8s0               
  meteor                                      
                                              
If you are new to Meteor, try some of the learning resources here:
  https://www.meteor.com/tutorials            
                                              
To start with a different app template, try one of the following:

  meteor create --bare    # to create an empty app
  meteor create --minimal # to create an app with as few Meteor packages as possible
  meteor create --full    # to create a more complete scaffolded app
  meteor create --react   # to create a basic React-based app
                                              
audited 601 packages in 2.227s
found 0 vulnerabilities

=> Errors while initializing project:         
                                              
While selecting package versions:
error: No version of standard-minifier-js satisfies all constraints: @1.2.2, @~2.4.0
Constraints on package "standard-minifier-js":
* standard-minifier-js@1.2.2 <- top level
* standard-minifier-js@~2.4.0 <- top level

/home/daniel/exp/MCB/React-Meteor-Todo-app/node_modules/execa/index.js:277
		throw (result.error || new Error(result.stderr === '' ? result.stdout : result.stderr));
		^

Error: null
    at Function.module.exports.sync (/home/daniel/exp/MCB/React-Meteor-Todo-app/node_modules/execa/index.js:277:26)
    at Object.bundle (/home/daniel/exp/MCB/React-Meteor-Todo-app/node_modules/meteor-client-bundler/lib/bundler.js:72:9)
    at Command.<anonymous> (/home/daniel/exp/MCB/React-Meteor-Todo-app/node_modules/meteor-client-bundler/cli:37:13)
    at Command.listener (/home/daniel/exp/MCB/React-Meteor-Todo-app/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (/home/daniel/exp/MCB/React-Meteor-Todo-app/node_modules/commander/index.js:651:12)
    at Command.parse (/home/daniel/exp/MCB/React-Meteor-Todo-app/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/home/daniel/exp/MCB/React-Meteor-Todo-app/node_modules/meteor-client-bundler/cli:45:9)
    at Module._compile (module.js:652:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-meteor-todo-app@ bundle-meteor-client: `meteor-client bundle -s api --url=localhost:8000`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-meteor-todo-app@ bundle-meteor-client script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/daniel/.npm/_logs/2018-11-16T17_32_53_381Z-debug.log
```

**Comment by Muhammad-Zaryaab-Shahbaz** [comment]
Do we have any solution for this?
